# Generated by Django 3.2.5 on 2021-09-29 14:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_hostel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
