# Generated by Django 3.2.5 on 2021-09-29 16:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_notice_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='default.png'),
        ),
    ]
