# Generated by Django 3.2.5 on 2021-09-29 16:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210929_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=None),
        ),
    ]
