# Generated by Django 3.2.5 on 2021-09-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_notice_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomallotment',
            old_name='room_allotted',
            new_name='alloted',
        ),
    ]
