# Generated by Django 3.2.5 on 2021-09-30 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_room_allotted_roomallotment_alloted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_no', models.CharField(blank=True, max_length=10, null=True)),
                ('total_seats', models.BigIntegerField(blank=True, null=True)),
                ('seats_available', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='transport',
        ),
        migrations.CreateModel(
            name='busReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(blank=True, max_length=20, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.bus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainapp.student')),
            ],
        ),
    ]
