# Generated by Django 3.2.5 on 2021-09-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210930_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus',
            new_name='SchoolBus',
        ),
    ]
