# Generated by Django 3.2.5 on 2021-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_rename_bus_schoolbus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolbus',
            name='total_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
