# Generated by Django 3.2.5 on 2021-09-30 11:43

from django.db import migrations, models
import mainapp.transport.transportModel


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_schoolbus_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='busreservation',
            name='status',
            field=models.CharField(blank=True, choices=[(mainapp.transport.transportModel.ReservationStatus['Active'], 1), (mainapp.transport.transportModel.ReservationStatus['Inactive'], 0)], default=mainapp.transport.transportModel.ReservationStatus['Inactive'], max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolbus',
            name='bus_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
