# Generated by Django 3.2.5 on 2021-09-30 11:47

from django.db import migrations, models
import mainapp.transport.transportModel


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210930_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busreservation',
            name='status',
            field=models.CharField(blank=True, choices=[(mainapp.transport.transportModel.ReservationStatus['Active'], 'Active'), (mainapp.transport.transportModel.ReservationStatus['Inactive'], 'Inactive')], default=mainapp.transport.transportModel.ReservationStatus['Inactive'], max_length=10),
        ),
    ]
