# Generated by Django 3.2.5 on 2021-09-30 12:27

from django.db import migrations, models
import mainapp.transport.transportModel


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_busreservation_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busreservation',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default=mainapp.transport.transportModel.ReservationStatus['Inactive'], max_length=10),
        ),
    ]
